# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesinfo',
            name='date_of_match',
            field=models.DateTimeField(null=True),
        ),
    ]
