# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160108_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship_sponsors_teams',
            old_name='sp',
            new_name='sponsor',
        ),
        migrations.RenameField(
            model_name='relationship_sponsors_teams',
            old_name='t',
            new_name='team',
        ),
    ]
