# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20160108_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachsinfo',
            name='coach_country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='coachsinfo',
            name='coach_name',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='playersinfo',
            name='player_name',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teamsinfo',
            name='country_name',
            field=models.CharField(max_length=2),
        ),
    ]
